# Generated by Django 5.2.17 on 2026-10-05 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_label', models.CharField(max_length=300)),
                ('pickup_label', models.CharField(max_length=300)),
                ('dropoff_label', models.CharField(max_length=300)),
                ('current_cycle_used', models.FloatField(help_text='Hours already used in the 70-hr/8-day cycle')),
                ('start_time', models.DateTimeField(help_text='Departure, home-terminal local time')),
                ('total_miles', models.FloatField()),
                ('total_days', models.PositiveIntegerField()),
                ('compliant', models.BooleanField(default=True)),
                ('result', models.JSONField(help_text='Full API payload: route, stops, logs, summary')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
